global using Moq;
global using Xunit;
global using FluentAssertions;
global using AutoFixture;
global using Post.Command.Domain.Events;
global using Post.Command.Domain.Commands;
global using Post.Command.Application.Commands;
global using Post.Command.Application.Interfaces;
global using Post.Command.Domain.Aggregates;